(setq tab-width 4)
(setq indent-tabs-mode nil)
(setq tab-stop-list (number-sequence 4 200 4))
(setq scroll-step 2)
(setq prelude-flyspell nil)
(setq prelude-guru nil)
(setq create-lockfiles nil)
(setq whitespace-line-column 120)
